const DISTRICT_LIST = [
    {label: "Dhaka", value: "dhaka"},
    {label: "Faridpur", value: "faridpur"},
    {label: "Gazipur", value: "gazipur"},
    {label: "Gopalganj", value: "gopalganj"},
    {label: "Jamalpur", value: "jamalpur"},
    {label: "Kishoreganj", value: "kishoreganj"},
    {label: "Madaripur", value: "madaripur"},
    {label: "Manikganj", value: "manikganj"},
    {label: "Munshiganj", value: "munshiganj"},
    {label: "Mymensingh", value: "mymensingh"},
    {label: "Narayanganj", value: "narayanganj"},
    {label: "Narsingdi", value: "narsingdi"},
    {label: "Netrokona", value: "netrokona"},
    {label: "Rajbari", value: "rajbari"},
    {label: "Shariatpur", value: "shariatpur"},
    {label: "Sherpur", value: "sherpur"},
    {label: "Tangail", value: "tangail"},

    {label: "Bogura", value: "bogura"},
    {label: "Joypurhat", value: "joypurhat"},
    {label: "Naogaon", value: "naogaon"},
    {label: "Natore", value: "natore"},
    {label: "Chapainawabganj", value: "chapainawabganj"},
    {label: "Pabna", value: "pabna"},
    {label: "Rajshahi", value: "rajshahi"},
    {label: "Sirajganj", value: "sirajganj"},

    {label: "Dinajpur", value: "dinajpur"},
    {label: "Gaibandha", value: "gaibandha"},
    {label: "Kurigram", value: "kurigram"},
    {label: "Lalmonirhat", value: "lalmonirhat"},
    {label: "Nilphamari", value: "nilphamari"},
    {label: "Panchagarh", value: "panchagarh"},
    {label: "Rangpur", value: "rangpur"},
    {label: "Thakurgaon", value: "thakurgaon"},

    {label: "Barguna", value: "barguna"},
    {label: "Barisal", value: "barisal"},
    {label: "Bhola", value: "bhola"},
    {label: "Jhalokathi", value: "jhalokathi"},
    {label: "Patuakhali", value: "patuakhali"},
    {label: "Pirojpur", value: "pirojpur"},

    {label: "Bandarban", value: "bandarban"},
    {label: "Brahmanbaria", value: "brahmanbaria"},
    {label: "Chandpur", value: "chandpur"},
    {label: "Chattogram", value: "chattogram"},
    {label: "Cumilla", value: "cumilla"},
    {label: "Cox's Bazar", value: "coxs-bazar"},
    {label: "Feni", value: "feni"},
    {label: "Khagrachhari", value: "khagrachhari"},
    {label: "Lakshmipur", value: "lakshmipur"},
    {label: "Noakhali", value: "noakhali"},
    {label: "Rangamati", value: "rangamati"},

    {label: "Habiganj", value: "habiganj"},
    {label: "Moulvibazar", value: "moulvibazar"},
    {label: "Sunamganj", value: "sunamganj"},
    {label: "Sylhet", value: "sylhet"},

    {label: "Bagerhat", value: "bagerhat"},
    {label: "Chuadanga", value: "chuadanga"},
    {label: "Jashore", value: "jashore"},
    {label: "Jhenaidah", value: "jhenaidah"},
    {label: "Khulna", value: "khulna"},
    {label: "Kushtia", value: "kushtia"},
    {label: "Magura", value: "magura"},
    {label: "Meherpur", value: "meherpur"},
    {label: "Narail", value: "narail"},
    {label: "Satkhira", value: "satkhira"}
] as const;

export default DISTRICT_LIST;